languageCode = "de-de"
title = "CIB Proto Site"
DefaultContentLanguage = "es"
theme = "cib-theme"
[languages]
    [languages.de]
        LanguageName = "Deutsch"
    [languages.en]
        LanguageName = "English"
